### ISSUE TITLE
Issue with Setting Up Unix for Java Development

### ISSUE THREAD

**Issue by CodingWhiz1234** [nus-cs2030/2324-s1#1]
# Summary 
I am trying to set up Unix for Java Development but I am unable to do so. 

## Description 
After running the command "irm get.scoop.sh | iex", I face the following error shown in the image below.

## Screenshots (if any): 

![Untitled](https://github.com/nus-cs2030/2324-s1/assets/142206064/5ba1dd46-c556-45c5-942c-f54b6322f9e3)

**Comment by hwkchia** [comment]
May I suggest you download and install separately?

```
irm get.scoop.sh -outfile 'install.ps1'
.\install.ps1
```

**Comment by CodingWhiz1234** [comment]
Hi, I tried what you suggested but it doesn't solve the problem.

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/c43cb956-c600-4725-a6b7-9e4efba74524)

**Comment by hwkchia** [comment]
Not sure if it's a because you need to be an adminstrator.  Try opening powershell as adminstrator and then do
```.\install.ps1 -RunAsAdmin```

**Comment by CodingWhiz1234** [comment]
Ah yes, what you have suggested solved my problem. Thank you!

I do have one more thing I would like to check. Is the msys file that I am supposed to open looks like the picture below?
![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/413b901f-67c8-4d98-b7af-5c61f6bcb91c)

When I search msys onto my "start menu" I am directed to this file below which doesn't seem like what I am supposed to open.
![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/667b031a-80b4-450b-a53a-da9b0a860439)

After some manual searching, I managed to find this msys.bat that seems like what I am supposed to open. Am I right?
![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/efe6a6cd-61ad-431a-b51b-90a6e1baf4b3)

**Comment by hwkchia** [comment]
Looks good to go! 👍
