### ISSUE TITLE
Lab 3: Multiple output detected

### ISSUE THREAD

**Issue by melinenl** [nus-cs2030/2324-s1#100]
# Summary

For my lab 3 I got this compilation error but I'm not sure what it means and what to do?

## Description:

I googled and it says that basically my code brings more than one output, but when I test internally on my laptop I don't see more than one output? 

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/148039935/10823782-0435-4381-81fe-10b6a9d912c8)

**Comment by PVT-LF** [comment]
See #85 and #14. Just remove all the unnecessary `System.out.println` calls apart from your final output, even in unused methods.
