### ISSUE TITLE
Ex 5: only one orElseThrow allowed

### ISSUE THREAD

**Issue by kirin46** [nus-cs2030/2324-s1#102]
Hello, I'm getting the error Only one orElseThrow allowed on codecrunch. May I know why is only one orElseThrow allowed? I thought that it is needed for both of(T value) and of(T value, String log).
Thanks in advance!

**Comment by wjunwei2001** [comment]
I think that is just a limitation set by the system. One way to get pass this is to use orElseThrow in of(T value, String log), and have of(T value) return a "of(T value, String log)". In this way, you will essentially check for both factory methods

**Comment by kirin46** [comment]
oh yes why didn't i think of that.. thanks for your help!
