### ISSUE TITLE
Logging Level5.jsh- Reverse output order 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#105]
<img width="198" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/00adb9a2-bc0d-4cfb-87af-5451d553b96b">
<img width="179" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/f11ca23f-ca89-440e-8f56-d88ed2cf3fff">

hi how do i reverse the output order? thanks!

**Comment by ChoonHean** [comment]
Trace your code and figure out how your program is running, then modify your code to get the output you want. If you want a certain order, then you must use flatMap in a certain order as well, not just in any order

**Comment by velouriaa** [comment]
solved thanks
