### ISSUE TITLE
How does reduce work 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#106]
Stream.iterate(Num.zero(), x -> !x.equals(n), x -> x.succ())
                .reduce(this, (x, y) -> x.succ());

Hi how does reduce work in the code above? thanks!

**Comment by ChoonHean** [comment]
It calls x.succ() on the identity/accumulated value for each element in the stream

**Comment by saddle196883** [comment]
To add on, the pattern
```java
result = Stream
    .iterate(seed, nonTerminatingCondition, unfolder)
    .reduce(defaultValue, (x, y) -> f(x, y));
```
is equivalent to (in pseudo-java)
```java
result = defaultValue;
for (Type y = seed; nonTerminatingCondition(y); unfolder(y)) {
    result = f(result, y);
}
```
In your case, the pattern is equivalent to the for loop
```java
Num result = this;
for (Num num = Num.zero(); !num.equals(n); num = num.succ()) {
    result = result.succ();
}
```
In other words, it just calls ``succ`` a total of ``n`` times on ``this``.

**Comment by velouriaa** [comment]
i see thanks!
