### ISSUE TITLE
Indv Proj- how to track avg wait time, served and left 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#108]
![image](https://github.com/nus-cs2030/2324-s1/assets/147584805/c2fea78b-129a-45ba-968e-c0733a3b047a)

Hi i have a method to get wait time, served and left in each event class, hence the need for constants to return 0.0,/0/1 for each class. But as a result im getting this error.

**Comment by saddle196883** [comment]
If you read the checkstyle xml file, you do not need to declare constants for 0 and 1.

**Comment by velouriaa** [comment]
i see thanks!
