### ISSUE TITLE
problem with jShell

### ISSUE THREAD

**Issue by gohqingkhang** [nus-cs2030/2324-s1#11]
[#]([url](url)) Summary
vim works with no issues, but there seems to be some problem with jShell.

## Description 
as can be seen, my jShell version is 19.0.1. also, typing "echo $TERM" results in cygwin.
1. seems to print ←[?2004h a lot, not too sure why
2. taking "lenovo@DESKTOP..." as line 1, line 6 is a result of "int a = 1"
3. sometimes when i try to backspace, it shows "←[D←[K" instead of backspacing

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s1/assets/143182152/3aa05e88-0b5b-4a43-8841-1fd5236d98d2)

**Comment by hwkchia** [comment]
Run the following command in msys:

`echo "TERM=dumb" >> ~/.profile`

Then exit and restart msys.  Test jshell and see if the issue still arises.

**Comment by AbdulrahmanAlRammah** [comment]
I applied the changes and it fixed the issue, but now there is a smaller issue. Whenever I enter a command I get an extra line of blank as though I have clicked enter:

jshell> /open Circle.java
/open Circle.java

jshell>

jshell> /open Point.java
/open Point.java

jshell>

jshell> new Point(0,0)
new Point(0,0)
$7 ==> point (0.000, 0.000)

jshell>

jshell>

**Comment by hwkchia** [comment]
The extra line is inconsequential.  But I have a hunch, could you show me the output of the following command in msys?
`which jshell`

**Comment by AbdulrahmanAlRammah** [comment]
![Screenshot (264)](https://github.com/nus-cs2030/2324-s1/assets/142239643/7da537fc-7e56-4474-b70a-0274cf2a0c7d)

**Comment by hwkchia** [comment]
You actually have another version of Java installed.  Do you mind removing the version from Add/Remove programs?  After that, I think you can also remove the `.profile` that you created, reboot your machine, and see if it still works.  The `which` command should point to `openjdk17` in the `scoop` directory.

**Comment by hwkchia** [comment]
Closed since no further responses on this matter.
