### ISSUE TITLE
Lab 4: Fail test case 9_11

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#110]
<img width="590" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/ad18e89d-5182-4274-9765-7d831758b771">

**Comment by ChoonHean** [comment]
At line 55, 13 was served by self-check 3, but at line 34, 15 was served by self-check 4. Since the self-checks share the same queue, a customer with a higher number should never be served before a customer with lower number. This means that your queue system isn't working as intended.

**Comment by vvivianfang** [comment]
> At line 55, 13 was served by self-check 3, but at line 34, 15 was served by self-check 4. Since the self-checks share the same queue, a customer with a higher number should never be served before a customer with lower number. This means that your queue system isn't working as intended.

if u look at the expected output, it is also like that..?

**Comment by Clementpng** [comment]
Hi I had encountered the same issue, one possible reason could be the updating of the Wait event's timing, where the timing is updated to the available time of the current self server rather than the available time of the earliest self server

**Comment by Zhou-Shude** [comment]
I met similar issue also.

My case was my wait event generated the repeating event at the server's time instead of the wait event's time

**Comment by yentheng0110** [comment]
Hello! I think in your Wait class, you should loop through the selfCheckList and determine which is the earliest self-check next available time and return that as the time stamp for Serve

**Comment by Rjun1** [comment]
> Hi I had encountered the same issue, one possible reason could be the updating of the Wait event's timing where the timing is updated to the available time of the current self server stored in Wait, rather than the available time of the earliest self server

I am facing the same issue and getting the same output too. However, my Wait event logic does cover this point of updating using the earliest self-checkout counter. Anyone knows what kind of other errors might be causing this?

**Comment by Zhou-Shude** [comment]
> > Hi I had encountered the same issue, one possible reason could be the updating of the Wait event's timing where the timing is updated to the available time of the current self server stored in Wait, rather than the available time of the earliest self server
> 
> I am facing the same issue and getting the same output too. However, my Wait event logic does cover this point of updating using the earliest self-checkout counter. Anyone knows what kind of other errors might be causing this?

Did you check the time that ur wait event generate the wait repeat event..
If the generation uses the server time, this situation will occur
E.g.

Customer wait at time x at server 1
Server 1 ready at time 10
So the repeat event is generated at time 10 instead of the next server's ready time

The logic should be
Wait event -> continue waiting at closest server time -> get served/wait agin..

For my case it was due to my wait event being a dummy event to be printing out the waiting lines and is immediately converted into a repeat waiting event that prints an empty line. So i had to use the event's time instead of server time to prevent repeating waiting to be generated at wrong time and causing this bug

**Comment by vvivianfang** [comment]
> > > Hi I had encountered the same issue, one possible reason could be the updating of the Wait event's timing where the timing is updated to the available time of the current self server stored in Wait, rather than the available time of the earliest self server
> > 
> > 
> > I am facing the same issue and getting the same output too. However, my Wait event logic does cover this point of updating using the earliest self-checkout counter. Anyone knows what kind of other errors might be causing this?
> 
> Did you check the time that ur wait event generate the wait repeat event.. If the generation uses the server time, this situation will occur E.g.
> 
> Customer wait at time x at server 1 Server 1 ready at time 10 So the repeat event is generated at time 10 instead of the next server's ready time
> 
> The logic should be Wait event -> continue waiting at closest server time -> get served/wait agin..
> 
> For my case it was due to my wait event being a dummy event to be printing out the waiting lines and is immediately converted into a repeat waiting event that prints an empty line. So i had to use the event's time instead of server time to prevent repeating waiting to be generated at wrong time and causing this bug
<img width="595" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/a5d49352-fcb8-4c9f-8705-395807fdd27c">

hi, in this portion it is saying what happens in the waitevent when server is not at frontofqueue(i.e. wait event has to be returned again). 

the first portion is if server is human
else is when server is not human. this gives me the 9_11 error

**Comment by vvivianfang** [comment]
or anyone else knows why im still facing this issue

**Comment by yentheng0110** [comment]
I think you should assign serverWithMinTime to servers.get(j) with the minTime, then return that as one of the attributes of the new ExtraWaitEvent

**Comment by vvivianfang** [comment]
> I think you should assign servers.get(j) with the minTime to a variable (example: serverWithMinTime), then return that as one of the attributes of the new ExtraWaitEvent

are u saying for this line, my server should be server(j) where j is the index of the server with the mintime?

pq.add(new ExtraWaitEvent(super.customer, server, minTime))

**Comment by ChoonHean** [comment]
> > At line 55, 13 was served by self-check 3, but at line 34, 15 was served by self-check 4. Since the self-checks share the same queue, a customer with a higher number should never be served before a customer with lower number. This means that your queue system isn't working as intended.
> 
> if u look at the expected output, it is also like that..?

No, for the expected output, 13 was served at line 33, 14 at line 37, and 15 at line 57. If they joined the same queue, the person customer who joined later cannot be served first

**Comment by ChoonHean** [comment]
Looking at your output, at line 32, 9 is done serving by self-check 4, so the next in the queue, 13, should be served next. However, 13 is not served, and 15 arrives and gets served. Make sure that your self-checkouts share the same queue, so that 13 is served first, and 15 queues at the self-checkout

**Comment by myonster** [comment]
> I think you should assign servers.get(j) with the minTime to a variable (example: serverWithMinTime), then return that as one of the attributes of the new ExtraWaitEvent

had a similar issue and this was the solution for me, initially I was just getting the time and not minimum time from the queue of self-checks
