### ISSUE TITLE
fail test case 9_9

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#126]
<img width="310" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/860d4f99-b57d-4f9e-b032-bfaa50564833">

i used random numbers and got this but why is it not arranged in order?

error for cc:

<img width="582" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/6e4415c4-df32-4680-b1e3-173261c3febc">

**Comment by IsaacNgSheng** [comment]
Seems like your polling/sorting of events is not based on time when it should be
