### ISSUE TITLE
Missing Circle.java, Point.java files in Ungraded Exercise

### ISSUE THREAD

**Issue by saddle196883** [nus-cs2030/2324-s1#128]
Could I ask, where can I find these files? I did not see it in the exercise. Maybe I had missed it. Thank you!

**Comment by kkaizee** [comment]
I think prof might had missed it while uploading. Maybe can try using the Circle and Point classes from exercise 1?

**Comment by andreelim** [comment]
yea just take from ex 1

**Comment by saddle196883** [comment]
Okay, I just had time to test, we can use the constructors in the Point and Circle classes from Exercise 1, as well as ``Circle.contains(Point p)``. I did not try to see if every method works, but this was enough.

Since this has been up for a few days, it is unlikely that prof will upload Circle.java and Point.java, so I will mark this as closed. Thanks for the help.
