### ISSUE TITLE
map() in Ungraded Exercise

### ISSUE THREAD

**Issue by katoro8989** [nus-cs2030/2324-s1#129]
Hi
Currently, i'm trying to figure out how i should define map() method, then i wondered if i should define it in such a way that we can use it many times like
`Rand.of(2030).map(x -> x - 1).map(x -> x % 2).get()`
Please tell me your opinions.

**Comment by YHWong20** [comment]
Haven't managed to solve it yet, but I was thinking the same thing as well. It also seems to me like the map() methods should be lazily evaluated too, though I am not too sure how I should go about doing this.

**Comment by YHWong20** [comment]
Hey! So I managed to solve it. 

It doesn't seem like map() is called multiple times (not according to the test cases at least), but I think it's fine to define the method in a way that can let you do so. 
So, the method signature should be similar to the map() we have in Optional and Stream, etc. So something like:
`<R> Rand<R> map(Function<T,R> mapper)`

**Comment by katoro8989** [comment]
Thank you @YHWong20 .
Like you said, it would be better if we design as we can implement map() many times.
So, i designed my class to have a Function in it so that we can implement it without forgetting map()s that we've already applied.

**Comment by katoro8989** [comment]
However, i came up with one more question here.
Which way should i code?

1. `<R> Rand<R> map(Function<T,R> mapper)`
2. `<R> Rand<R> map(Function<? extends T, ? super R> mapper)`

**Comment by saddle196883** [comment]
The exercise indicates not to use wildcards.
