### ISSUE TITLE
Cannot enter insert mode in vim

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2030/2324-s1#13]
# Summary
I am in the unix environment, but when I enter vim editor. I cannot enter insert mode

## Description 
I can press esc and key ":q!". I also have tried hitting esc a few times, and afterwards pressing "i", it does not insert

## Screenshots (if any): 

https://github.com/nus-cs2030/2324-s1/assets/143115667/025c39b4-12c1-451f-9a9a-f290990007e7

**Comment by kyoeun-kim** [comment]
isn't the fact that you can type in things to vim mean you are already in insert mode?

**Comment by somethingfishyfishy** [comment]
Hi you are right that it is in insert mode (I used :q! instead of :wq). I did not know whether it was in insert mode as the "--INSERT--" was not seen at the bottom. 

THAT BEING SAID, backspace does not work in insert mode, not sure if this is an intended feature in insert mode <see 0:07 to 0:08>

**Comment by AbdulrahmanAlRammah** [comment]
Yeah backspace doesn't work in insert mode by default. You have to click escape then click x to delete. There are also shortcuts to delete words. There is a way to make backspace work that is on google, but I am not sure if we are allowed to change default settings of vim in PE.
