### ISSUE TITLE
ungraded assignment randRange

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#131]
<img width="1211" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/ab4d4a8c-af02-462b-8750-a23ff111910f">
why am i receiving this error when my inputs for the method is 

static <R> Stream<R> randRange(int seed, Function<? super Stream<Integer>, ? extends Stream<R>> mapper)

**Comment by limefreak** [comment]
Hmm the function is defined as 

Function<Integer,Integer> f = x -> x % 10

Parsed into randRange(2030, f). That looks like a Function<Integer, Integer> to me

**Comment by vvivianfang** [comment]
> Hmm the function is defined as
> 
> Function<Integer,Integer> f = x -> x % 10
> 
> Parsed into randRange(2030, f). That looks like a Function<Integer, Integer> to me,
> 
> I don't think Integer extends Stream....

but the output is Stream<Integer>?

**Comment by limefreak** [comment]
Yes, overall you may take in a stream and output a stream, that depends on how you code it, but the function f itself takes in an integer and returns a boolean. If you stream through a list and map it with f, you get another stream, but that's a different function for you to define.

**Comment by vvivianfang** [comment]
> Yes, overall you may take in a stream and output a stream, that depends on how you code it, but the function f itself takes in an integer and returns a boolean. If you stream through a list and map it with f, you get another stream, and that's a different function for you to define.

isnt boolean for map? not randRange

**Comment by limefreak** [comment]
Oh right,  
map is Function<Integer, ? extends Object> 
randRange is Function<Integer, Integer>,
my bad. I'm messed up there lmao

**Comment by limefreak** [comment]
At a later part, randRange should be opened to other object types too
Rand.randRange(2030, x -> String.format("[%02d]", x % 100))
