### ISSUE TITLE
<T> Maybe <T> vs Maybe<T>

### ISSUE THREAD

**Issue by e0970359** [nus-cs2030/2324-s1#133]
when do we have to add the extra <T> infront ?

**Comment by AbdulrahmanAlRammah** [comment]
The extra is for when you are defining a new generic variable. Like lets your class has a Maybe<T> attribute and one of your functions is a mapping from T to R then your output would be <R> Maybe<R>. The first <R> defines the new generic type and the Maybe<R> is your output.

**Comment by saddle196883** [comment]
When one does:
```java 
class Class<T> {
    // blurb blurb blurb
}
```
the type T is bound already to a specific type. Thus the only situations where you need to have extra <R> are when:
- the method is static (so no bindings have occured), e.g. in ``static <T> Class<T> of(T innards)``; and/or
- the method has additional generic classes not bound in the front, e.g. in ``<R> Class<R> map(Function<T, R> mapper)``.
