### ISSUE TITLE
For PA2, do we have to worry about importing the necessary libraries? 

### ISSUE THREAD

**Issue by e0958029** [nus-cs2030/2324-s1#134]
In PA1 the import of Comparator was done automatically, so I wonder if it applies for this PA2 as well for optionals or the various functions.

**Comment by hwkchia** [comment]
You will need to import the necessary packages to make your code compilable in CodeCrunch.

**Comment by e0958029** [comment]
Shouldn't have risked it. Hopefully moderation is merciful T.T
