### ISSUE TITLE
Ungraded Exercise: Rand Level 3 map() method

### ISSUE THREAD

**Issue by nearsea00** [nus-cs2030/2324-s1#135]
# Summary

As suggested in [this thread](https://github.com/nus-cs2030/2324-s1/issues/132), I'm storing the mapper function in a private final attribute in my Rand class and applying it only when the client calls a get() or stream(). However, I'm having some issues with the default identity function.

## Description:
This is my constructor for when the client calls a static of(). Since there's no map() done yet, the default mapper function should just be an identity function.
`private Rand(Supplier<Integer> supplier) {
        this.supplier = supplier;
        this.function = x -> x;
    }`
However, I run into an error when I do this because the return type of the mapper function has to be a generic T to pass all of the test cases, but my supplier stores an Integer which can't be converted to a T. Is there a way to resolve this?

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/145828376/b608b4e9-2702-4b1b-ba36-c796d5f3e7bd)

**Comment by saddle196883** [comment]
How about you let your private constructor take in an ``int`` (I don't think a ``Supplier<Integer>`` is necessary) and a ``Function<Integer, T>``. Then the static of method returns a ``Rand<Integer>`` with the identity function you have.
 
```java
static Rand<Integer> of(int seed) { return new Rand<Integer>(seed, x -> x); }
```

**Comment by nearsea00** [comment]
That solved it, thank you!
Also yeah, I thought a supplier was necessary to do lazy evaluation, but since I'm storing the function in a variable and performing the map() at the very end that's pretty much lazy evaluation already. Thanks for the help.
