### ISSUE TITLE
PYP question

### ISSUE THREAD

**Issue by adamzzq** [nus-cs2030/2324-s1#142]
1. [8 marks] A university comprises two types of students: undergrads (UG) and post-grads (PG). Every student has a unique string identifier (id). A student can read modules and be credited marks at the end of the semester. These marks are managed by the Admin office (Admin) which has access to the list of students and their CAP (getCAP). CAP computation is the same for any type of student.
A student can also apply for study loans during their candidature. The Bursar’s office (Bursar) has access to the list of students and their loan amount (getLoan). Loan amounts are computed differently for different types of students. Notice that student CAP and loans are handled by different offices. Due to prevailing privacy data protection policies, no one party shall have access to data that does not come under the purview of the office.
We would like to design the high level structure of the classes and test the program with method stubs (or methods with dummy implementations). Define the classes PG, UG, Admin, Bursar and their dependencies; you may include other classes or interfaces.

Include the following methods where appropriate:
 double getCAP() which returns 5.0 for all students;
 double getLoan() which returns 99.99 for undergrads, and 111.11 for post-grads;
 String getId() which returns the student identifier.

In each of the Admin and Bursar classes, include separate process methods that takes in a list of students in order to “process” (for simplicity, to print out) the CAP and loan respectively for the students.

A sample run is shown below:
jshell> List<Student> students = List.<Student>of(
...> new UG("U123"), new PG("P456"))
students ==> [UG@39aeed2f, PG@724af044]

jshell> new Admin().process(students)
U123 : 5.0
P456 : 5.0

jshell> new Bursar().process(students)
U123 : 99.99
P456 : 111.11

Anyone can provide some insights as to how to encapsulate the Cap and Loan of students so that the respective offices have access to the necessary information only? 
I was thinking
approach 1: getLoan and getCAP should be private, however, if so, how does the information reach the offices?
approach 2: both Admin and Bursar inherit an interface Office, then the student.getCap and student.getLoan will check who is calling the method using instanceof. If the wrong office is calling the method, it will return a dummy value e.g. CAP = -999. But using instanceof seems to break the abstraction barrier so it might not be a good approach.

**Comment by kirin46** [comment]
My approach was to have two interfaces StudentLoan (with the getLoan method) and StudentGrade (with the getCap method), and Student will implement both these interfaces. In the Admin class, all calls to "Student" should be StudentGrade and in Bursar, should be StudentLoan. This way, the offices does not have access to the other office's info. Not necessary for a Admin and Bursar to inherit another interface as well.

**Comment by adamzzq** [comment]
> In the Admin class, all calls to "Student" should be StudentGrade and in Bursar, should be StudentLoan.

Thanks al lot, I tried this way you said, but I didn't get why a office will not have access to the other office's info. Because I think that there is no strict restriction for bursar to call StudentGrade and for Admin to call StudentLoan. e.g. the Admin class can still write a method such as `void peek(List<StudentLoan> students) { System.out.print(students.get(0).getLoan());}` to access the a student's Loan, or simply `void peek(List<Student> students) { System.out.print(students.get(0).getLoan());}` which has access to both the CAP and Loan by not programming to the interface

**Comment by kirin46** [comment]
> Because I think that there is no strict restriction for bursar to call StudentGrade and for Admin to call StudentLoan. 
 
I think the question requires that an office only has access to their own information, so there should be a strict restriction. Bursar should only be using StudentLoan (which doesn't have a getCap method), this way there no access to the grades
