### ISSUE TITLE
Scanner is not reading any of the input(?)

### ISSUE THREAD

**Issue by roderickvo** [nus-cs2030/2324-s1#15]
# Summary

Hello everyone, I am currently working on lab 1 but I think my Main.java is not reading any of the input(?) Because it keeps returning [0,0] and not putting anything into the ImList of arrivaltimes and service times. I would like to ask whether we have to modify anything on the Main.Java file or if anyone can help in resolving the issue? Thank you so much!!

## Description:
I put some line of codes to check the size of the ImList array for arrivaltimes and servicetimes and they both printed 0. 

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="325" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/143242823/419b29d0-c90d-45d6-99a5-96f01acffae7">

<img width="178" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/143242823/e5e164da-75c7-40ee-bd8a-894a9288c015">

Screenshots (if any)

**Comment by AbdulrahmanAlRammah** [comment]
The Main.java works as is. It is just that the Main.java is not an OOP solution and a functional one instead. If you changed something I suggest downloading the original main.java and trying again. Also, make sure your test case is done correctly. 

Small note, the main.java from the case is in lowercase main.java NOT Main.java. There is a function inside main.java which is capital Main. This maybe the issue. try java main.java < 2.in.

**Comment by roderickvo** [comment]
<img width="214" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/143242823/84465a4a-073c-4888-9b47-1e1aaa459c09">

Hello thank you for your reply! I have tried re-downloading the main.java and do as you said but still get the same result(?)

**Comment by roderickvo** [comment]
Hi thank you for your reply! I have tried re-downloading as you said but still received the same result
<img width="214" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/143242823/44ef6e86-3566-4b05-a3f9-f8b7f797c13a">

**Comment by somethingfishyfishy** [comment]
Did you have any elements in arrivalTimes & serviceTimes?

Your screenshot below does not show your results --> can't determine if its a code issue or otherwise. It could be that your code was working, except because your Lists were empty thats why it prints 0
> ![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/1abf0e73-536d-49d9-8f68-455826e7bb91)

For calling "java Main.java < 2.in", it is very possible that your 2.in file is empty
> ![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/4dd47218-3d42-4354-a323-21817c191afa)

If you see the codecrunch sample run, they created the input before calling that line
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/7e843047-3df3-492f-b695-df5a1a5e3efe)

**Comment by roderickvo** [comment]
Hi thank you for your reply! I realized that I have to use comma "," instead of a period "." when writing the input and everything has worked now. Thank you so much!
