### ISSUE TITLE
Checking of the Type of Class in the Priority Queue

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2030/2324-s1#17]
# Summary

My list of PriorityQueue contains a bunch of classes with the Event interface. Each time I .poll() and return .first() from the PriorityQueue, I need to find which of the following classes it is (Arrive, Serve, Leave, Done)

## Description:

However, the CodeCrunch prevents me from using instanceof or .getClass().equals(Arrive.class) and it always returns an F grade. Is there any way to combat it? And if I include an additional variable in each Class called firstEventofCustomer which is a boolean, true for Arrive but false for the other three, will that be accepted?

## Code Snippets
<img width="325" alt="Screenshot 2023-09-10 at 14 33 57" src="https://github.com/nus-cs2030/2324-s1/assets/142196043/a44c8ffd-b50e-46aa-8ca9-4dc4469ee30c">
<img width="228" alt="Screenshot 2023-09-10 at 14 33 22" src="https://github.com/nus-cs2030/2324-s1/assets/142196043/7f7c0578-eb9e-44cd-8a73-a11c10626ace">
<img width="328" alt="Screenshot 2023-09-10 at 14 34 27" src="https://github.com/nus-cs2030/2324-s1/assets/142196043/caee4190-ee3c-452f-ad98-d62421a9e706">

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by wjunwei2001** [comment]
If I'm not wrong, we are not supposed to be checking for the type of event in our Simulator class, but rather make use of polymorphism to ensure that the same method in each event class does different things. The firstEventofCustomer property is basically a property to check whether the event is an Arrive event. From what I heard from my TA, that is not what we should be doing, not sure if codecrunch would catch that

**Comment by claralumwm** [comment]
why not add another method in your Event interface that returns a String which specifies which event it is?

`interface Event {
    String getEventType();
}`

`
class Arrive {
    // your properties

    public String getEventType() {
        return "Arrive";
    }
}
`

**Comment by somethingfishyfishy** [comment]
> why not add another method in your Event interface that returns a String which specifies which event it is?
> 
> ```
> interface Event {
>     String getEventType();
> }
> ```
> 
> ```
> class Arrive implements Event {
>     public String getEventType() {
>         return "Arrive";
>     }
> }
> ```

@claralumwm I hope Prof Henry's reaction to your post gave you a hint that you (as the client) should not need to know what event type it is. Jun Wei's answer (before yours) is quite self-explanatory. 

To clarify, you (the client) only need know the method name that is common across the event types, except that the method does different things in different classes [an example could be that one method in the Arrive class - toString() gives a different String than the toString() method in the Leave class]. Hence, you only need to call Event.toString() without ever needing to identify the Event type itself.

> If I'm not wrong, we are not supposed to be checking for the type of event in our Simulator class, but rather make use of polymorphism to ensure that the same method in each event class does different things.
