### ISSUE TITLE
How to assign stronger access modifiers to child classes?

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2030/2324-s1#18]
# Summary
Context: I wrote Event as an abstract class. And the other classes such as Arrive inherited from Event.

## Description:
This is regarding one method I wrote in the abstract class, update(). In the Event class, update() was made to be an abstract public method. However, during compilation of the Arrive.java file, it throws an error when overriding saying attempting to assign weaker access privileges. However, on both I used public. Why is it that public methods on parent classes are "stronger" than public methods on child classes? 

Clarifications or details with respect to the issue you are facing
Code in Parent Class:
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/a57b1793-bf8a-44da-b2a0-46a17f7c272f)
Code in Child Class:
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/e836a2de-9697-4afe-b786-c1acb76a0d32)
Error thrown:
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/244555a2-81e3-4003-b1e4-0771fc36557e)

FYI:
One workaround was to drop the 'public' access modifier in the parent class

**Comment by hwkchia** [comment]
Did you check the `Serve` class?

**Comment by somethingfishyfishy** [comment]
Oh yes, that is also probably the issue. Thanks prof
