### ISSUE TITLE
When should I make javadoc comments in my classes?

### ISSUE THREAD

**Issue by Marcelleejx** [nus-cs2030/2324-s1#19]
When submitting Lab 2 on CodeCrunch, I ran into one compilation error:
Missing a Javadoc comment. [MissingJavadocMethod]

This led me to google what exactly is a Javadoc comment, and I found that writing this solved the checkstyle error:

![Screenshot 2023-09-13 at 11 38 24 PM](https://github.com/nus-cs2030/2324-s1/assets/144933935/914ca8e1-f8a4-42b3-9aef-e80ee0c68539)

However, I only ran into this error for one of my class's methods, and none of my methods have Javadoc comments (other than this one which I rectified)

I would like to understand the purpose and when I should comment like this! Thank you.

**Comment by ChoonHean** [comment]
If you define a public method then checkstyle requires you to have javadoc comments. Setting it to private/protected/no modifier(default package visibility) will not require javadoc comments

**Comment by piggyYuann** [comment]
I think the comments are required for all and it's a good habit to keep? As having the comments helps us to quickly preview what the methods are doing. You can have a look inside the ImList.java provided by prof, in which all the methods got their comments.

**Comment by hwkchia** [comment]
As long as you do not make your class `public`, you will not need to write documentation.  😄 

That being said, it's good to write documentation, but it's more important to write good documentation.  However, this is not a learning outcome of the course, and I would prefer to have another course teach you to write the right type of documentation.
