### ISSUE TITLE
Issue regarding Setting Up Unix for Java Development

### ISSUE THREAD

**Issue by Tanziyanghenry** [nus-cs2030/2324-s1#2]
I have managed to install everything but I am not able to find msys to type explorer.exe.
<img width="550" alt="Screenshot 2023-08-15 011115" src="https://github.com/nus-cs2030/2324-s1/assets/142252801/0d4e1fb0-24fd-4d7e-9371-ed4e806f37e5">

**Comment by PVT-LF** [comment]
Hi, assuming all went well with the installation it should be inside that folder. Open it and run the msys application inside the folder.

-Levant
