### ISSUE TITLE
Autograder (incorrectly) fails submission - false positive detection of use of "instanceof"

### ISSUE THREAD

**Issue by PVT-LF** [nus-cs2030/2324-s1#20]
# Summary

Autograder (incorrectly) fails submission - false positive detection of use of `instanceof`

## Reproduction

Create valid code with a suitable Simulator class. Add a comment, with `instanceof`, i.e. `instanceof` has been commented out.

E.g.: `// instanceof`

Upon submission to CodeCrunch the autograder fails the submission due to having "detected the use of `instanceof`".

The autograder does not does not check if the use of `instanceof` was commented out, resulting in the autograder failing a submission even though `instanceof` was commented out and not used at all.

**Comment by hwkchia** [comment]
I've fixed the grader.  Kindly provide the submission id so I can test?

**Comment by PVT-LF** [comment]
> I've fixed the grader. Kindly provide the submission id so I can test?

Hi Dr Chia,

My user ID is e0957361 on CodeCrunch.
2542725 and 2542727 seem to be the submissions where in PQComp.java even after I had commented out the parts with `instanceof` it was still considered as being used by the autograder.

Sorry for the late reply.

**Comment by hwkchia** [comment]
Thanks for assisting with verify.  I shall close the issue now.
