### ISSUE TITLE
Is it possible to downcast a reference not explicitly?

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2030/2324-s1#21]
# Context
Event is an Abstract Class
Arrive inherits from Event
In the Simulator class, there is a loop that polls Events from PQ. When an Event is polled, if it is an Arrive event, I would call Arrive methods, meaning I will need to "cast" the Event as Arrive class to access the Arrive methods.
// Search up casting if you do not know what it means, it will be helpful for the future 

## Description:
The issue is that codecrunch rejects explicit downcasting (see screenshots). I have tried using instanceof but that does not seem to work either.
If this is the wrong direction to go, what should be the way to access methods in child classes?

## Screenshots
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/af74c510-370e-46d3-bc2d-de56aef196f2)
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/f903159b-1ea8-4c43-8e5e-69095fcfee39)

**Comment by adamzzq** [comment]
I think explicit typecasting is not encouraged in this course, and the use of `instanceof` keyword is also banned. maybe try to use polymorphism?

**Comment by ChoonHean** [comment]
https://github.com/nus-cs2030/2324-s1/issues/17#issuecomment-1713936687
Do what you said here, there is no need to know what class it is

**Comment by somethingfishyfishy** [comment]
Hi all, thanks for clarifying. 
I thought Arrive Events were special, hence the special treatment of Arrive methods. I have figured out what to do. Thanks
