### ISSUE TITLE
Fail Test Case: 1 Too many service times generated

### ISSUE THREAD

**Issue by Marcelleejx** [nus-cs2030/2324-s1#22]
# Summary
In my code, i only called getServiceTime() once, in a class, however I am failing the test case. My program gives me the output as shown in the lab Task Content test outputs on my own testing. Any clue as to why I am running into this error?

## Screenshots
![image](https://github.com/nus-cs2030/2324-s1/assets/144933935/c57c1578-39fb-434a-a2bd-bf82098e0c57)

**Comment by nearsea00** [comment]
Where are you calling getServiceTime()? I ran into the same issue and in my case, the problem was that I was calling getServiceTime() even when the customer left. I solved it by calling it under my Serve event class.

**Comment by wjunwei2001** [comment]
This error means that getServiceTime() is called more than once for at least one Customer. Perhaps can trace through what a customer can go through and see where getServiceTime() is called the second time. According to the lab info, getServiceTime() should be called only when the Serve event is being executed

**Comment by limefreak** [comment]
If your code compiles and you are willing to test whenever your code goes for "getServiceTime()", you can print a statement each time it is called. This helps you tell when you should/should not be calling "getServiceTime()".

![image](https://github.com/nus-cs2030/2324-s1/assets/97215727/4c6832ff-cc52-4e9d-8d11-3545d1bf3448)
