### ISSUE TITLE
Illegal Format Conversion Exception 

### ISSUE THREAD

**Issue by e0970359** [nus-cs2030/2324-s1#24]
# Summary
what does this error mean?
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="642" alt="Screenshot 2023-09-25 at 5 35 37 PM" src="https://github.com/nus-cs2030/2324-s1/assets/145977561/41168eec-7132-4f0f-b4cc-e5c4c9160496">

Screenshots (if any)

**Comment by limefreak** [comment]
Looks like you tried to compare a variable to a class there? 
d != Customer looks a bit like 
7 != Integer
It's bombing you to tell you that that's illegal.
