### ISSUE TITLE
Lab 3 test case 7

### ISSUE THREAD

**Issue by limefreak** [nus-cs2030/2324-s1#25]
# Summary

Not sure what went wrong... I died at test case 7

## Description:
1. Submit files to codecrunch
2. Obtain wrong output at test case 7
3. Confusion

I suspect it has something to do with time passing through my Serve to Done events, but it's strange to have test cases 1-6 passed. Before I take a deep breath and analyze my code completely, anyone faced this problem and resolved it?

## Code Snippets

Not sure if I can do this

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/97215727/d0fec785-1f79-4a69-940c-9f6c9e4f3e5b)

Expected output on the left, my output on the right

**Comment by limefreak** [comment]
Resolved, I called getServiceTime() in the arrive to wait interface. Supposed to call getServiceTime() in the wait to serve interface.

**Comment by kirin46** [comment]
hi, I am also facing the same error as you did but i did not call getServiceTime() in the arrive but only in wait or serve. Any other changes you made that helped you resolve this error? thank you!

**Comment by limefreak** [comment]
Hmmm. The only possibility is that you called getServiceTime() when going from wait > wait, and not from wait > serve. You only call the function when you are going to serve the customer.

**Comment by kirin46** [comment]
yes, that was my mistake, thank you for helping!
