### ISSUE TITLE
Autograder: Unable to use protected access modifier in Mock PA?

### ISSUE THREAD

**Issue by PVT-LF** [nus-cs2030/2324-s1#26]
## Description:
I used an abstract class `Driver` which would have various children like `NormalCab` and `PrivateCar`, and the 2 attributes below cannot be made `protected` instead of `private` so the children may access them.

I can obviously use a workaround by having these attributes `private` in the children classes but that is against the purpose of inheritance.

This was not an issue for Lab 2 which is why I find this odd. The original question states that the code should be designed to allow the addition of other services and driver types which warrants the use of inheritance rather than completely separate classes.

EDIT: I reread the question and apparently only `private final` attributes are allowed (for some reason). Or should I assume that since the question did not state that inheritance should be used, inheritance should not be used at all unless explicitly stated?

Sample Code:
```
abstract class Driver {
    protected final String licenseNumber;
    protected final int waitingTime;

    Driver(String licenseNumber, int waitingTime) {
        this.licenseNumber = licenseNumber;
        this.waitingTime = waitingTime;
    }

    public int getTime() {
        return this.waitingTime;
    }
}
```
Autograder output:

```
field licenseNumber in class Driver
field waitingTime in class Driver
not declared private final
Grading terminated.
```

**Comment by WinstonJin** [comment]
You can use private final modifiers in your parent classes. But you can also implement getter functions in your parent class that your child class can call.

For example your licenseNumber, add a method in Driver class called "public String getLicenseNumber()" which returns "this.licenseNumber". In your child class you can just do super.getLicenseNumber() to get the parent's licenseNumber

**Comment by PVT-LF** [comment]
I realise that I had assumed the `protected` access modifier in Java functions similar to that in C++, which is not the case as all classes in the same package can access `protected` methods and attributes. So it's just better to use a `private` modifier in most cases.
