### ISSUE TITLE
ImList sort thru comparable require Null Value.

### ISSUE THREAD

**Issue by roydenteh99** [nus-cs2030/2324-s1#27]
# Summary

I wish use ImList sort that sort thru comparable, in the doc it is mentioned use null value but when i do that code crunch doesnt accept my answer.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by hwkchia** [comment]
Our restrictions in usage of `null` overrides the use in the API.
