### ISSUE TITLE
zsh: permission denied:

### ISSUE THREAD

**Issue by jjiehh** [nus-cs2030/2324-s1#3]
![image](https://github.com/nus-cs2030/2324-s1/assets/142228944/60e69960-64a9-47b7-92cd-03da486c335c)
the above image shows the steps i need to do since my homebrew is not in my path after installing it. 

<img width="530" alt="Screenshot 2023-08-15 at 12 17 59 PM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/3bccb45e-6ce7-4a50-9e08-29e9909d0696">
the above image also shows the steps after i installed jdk17 

but above all, i keep receiving "zsh: permission denied:" 

does anyone how to troubleshoot this issue? thank you.

**Comment by hwkchia** [comment]
So you managed to install openjdk17?  What did you do to "keep receiving zsh:permission denied".  Could you show me the output of ```which jshell``` in the terminal window?

**Comment by jjiehh** [comment]
<img width="671" alt="Screenshot 2023-08-15 at 6 30 57 PM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/6b6fb3ac-50a8-42b5-8f17-102b46a2990e">
i cant see any jshell, it only shows "(base)".

**Comment by hwkchia** [comment]
I mean type `which jshell` in the mac terminal and press return.  Show me the output?

**Comment by jjiehh** [comment]
<img width="354" alt="Screenshot 2023-08-15 at 9 33 16 PM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/6cc68187-90a6-4ec2-8a53-d74270b23afd">

**Comment by hwkchia** [comment]
it's `jshell` not `shell`

**Comment by jjiehh** [comment]
<img width="373" alt="Screenshot 2023-08-16 at 2 12 01 PM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/07c9c968-d37b-4613-b5f4-8ba59919e1c8">
my apologies but here is the output

**Comment by hwkchia** [comment]
So everything is setup properly?  You can use `jshell` now?

**Comment by jjiehh** [comment]
i was unable to get msys window to open up in my mac. or is it only windows is applicable to this?

**Comment by hwkchia** [comment]
msys is for Windows.  For Mac, refer to
[https://github.com/nus-cs2030/2324-s1/wiki/Setting-up-Unix-for-Java-Development#setup-for-mac](url)
