### ISSUE TITLE
Mock PA#1 Cannnot Use java.util.object Error

### ISSUE THREAD

**Issue by roderickvo** [nus-cs2030/2324-s1#32]
# Summary

Hello Everyone, I submitted my Mock PA on CodeCrunch earlier today and I received an error for using Java.util.object if I remember correctly. I was wondering whether it might be caused because I used ImList and a Comparator to sort my ImList for the findBestBooking method? For my Comparator I used the compareTo method that I have defined at my Booking class. Thank you

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by nearsea00** [comment]
I used the same method that you're describing and I didn't encounter any issues so I don't think that's the problem.

Can you check the test output on CodeCrunch again? It usually specifies the snippet of code that's causing the issue.

**Comment by somethingfishyfishy** [comment]
please share more information.

If you used "implements Comparator", codecrunch would have rejected automatically because you are not allowed to use that. Please elaborate what you mean by Comparator.

There's probably more information in the test output to tell you where exactly you are using java.util.object wrongly.

**Comment by roderickvo** [comment]
Hello thank you for your reply. This is the only output I got

<img width="215" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/143242823/3625e587-9dc8-45fb-b926-845b0e1e5910">

**Comment by nearsea00** [comment]
The Comparator interface isn't actually disallowed for this submission (third bullet point).
![image](https://github.com/nus-cs2030/2324-s1/assets/145828376/66f6edac-4f81-495f-a319-46d666dfedf6)
I also used a Comparator interface in my code and CodeCrunch didn't reject it.

**Comment by roderickvo** [comment]
Ohh I managed to get over the issues. Turns out I forgot to put private static on my constant variables.
