### ISSUE TITLE
cyclic dependency issue

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#36]
computeFare method take in a trip as a Trip, but Trip is dependent on Fare , how do i solve this cyclic dependency issue?

interface Fare {
    public int computeFare(Iterable<Ride> trip);
}

jshell> trip.fare(sfare)
$.. ==> 110

**Comment by nearsea00** [comment]
computeFare is taking in an Iterable, not the Trip class, so there's not actually any dependency within Fare

**Comment by velouriaa** [comment]
i see thank you!
