### ISSUE TITLE
Lab 5 Deadline

### ISSUE THREAD

**Issue by roderickvo** [nus-cs2030/2324-s1#37]
# Summary

Dear Professor,

I would like to ask about when is the deadline for Lab 5(the one we just had today). Thank you!

**Comment by somethingfishyfishy** [comment]
You can see it on codecrunch. It says 13 Nov
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/9642ad0c-6ebf-4518-a3c5-c4f0a632dfa4)
