### ISSUE TITLE
Time limit exceeded in CodeCrunch

### ISSUE THREAD

**Issue by ChoonHean** [nus-cs2030/2324-s1#39]
## Description:
I ran into the issue of time limit exceeded in CodeCrunch, and i am unable to rectify it. Does CodeCrunch consider it an infinite loop after a certain amount of time, or after a certain number of iterations? Because this test case has 160+ customers, and i passed the previous 12 test cases, I am not sure if my code is just not efficient enough or it is in an infinite loop.

## Screenshots
![Capture](https://github.com/nus-cs2030/2324-s1/assets/145236676/fe890f1d-1b4d-4bff-b717-f4cac7217db1) Summary

**Comment by somethingfishyfishy** [comment]
There is probably an infinite loop. If you create an input file and feed in the data of arrival times (as well as the 3 ints and 1 double for the first line --> numServers numSelfChecks qmax probWait), and you run that input file in **terminal** into Main using

`java Main < 1.in`

_Do make sure you compile all relevant files in terminal before running in terminal. You can use_
`javac *.java`

If you don't see a new command line in terminal, there is an infinite loop.

I also encountered quite a couple of infinite loop as well, but not this test case. Just try to figure out what is causing your infinite loop even if you have 160 customers. All the best.

**Comment by jinnsuke** [comment]
Most likely an infinite loop or you could be using a higher order function that is recursing endlessly causing this fault. As mentioned above, can try to compile in order to find out which class is the issue. 

All the best!
