### ISSUE TITLE
Issue with setting up msys 

### ISSUE THREAD

**Issue by roydenteh99** [nus-cs2030/2324-s1#4]
I have similar issue like the other thread,I Opened the folder and click on msys bat and it show this error.
Please advice
![image_2023-08-15_154039237](https://github.com/nus-cs2030/2324-s1/assets/43632407/f049478c-50f0-4559-b159-bfee2c19d3d4)

**Comment by hwkchia** [comment]
Could be due to your user name with spaces.  Could you try creating another user with no spaces?
