### ISSUE TITLE
How to implement flatMap method in Maybe?

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2030/2324-s1#41]
# Description
In lecture, (1hr 14mins ~1hr 21mins), Prof goes through how to implement the map method in Maybe.
I understand the concept of flatMap method, but I have no idea how to implement the flatMap method.

This is related to the or(Supplier) method in Exercise 4.

## Screenshots
The screenshot below is what I implemented for the or method in Maybe. I think there is some Maybe[Maybe[T]] involved hence the failure to compile. (unless I'm wrong, then I actually don't know what's causing the failure to compile)
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/00795eb1-7003-417a-b0ad-8c72c7cd6b3a)

**Comment by Green-Tea-123** [comment]
I'm pretty sure it's because you cannot assign a Maybe<? extends T> to a Maybe<T> and your supplier is getting an object that is a Maybe<? extends T>.

**Comment by G13nd0n** [comment]
i think you can try get the supplier.get() seperately as a variable then return the variable if the Maybe is empty cause that worked for me

**Comment by vvivianfang** [comment]
using supplier.get() is not sufficient because the return type may not be Maybe<T>, hence u need to use map

**Comment by hwkchia** [comment]
Why is `try.. catch` being used if the problem is not about handling exceptions?

**Comment by somethingfishyfishy** [comment]
> i think you can try get the supplier.get() seperately as a variable then return a Maybeof(variable.get()) if the Maybe is empty cause that worked for me
Took me 4 days to understand what you mean, thanks tho

> using supplier.get() is not sufficient because the return type may not be Maybe, hence u need to use map
Not sure if you were trying to confuse me or you yourself was confused, I did not understand it. Also did not help towards the task at hand.

> Why is `try.. catch` being used if the problem is not about handling exceptions?
Saw in the Optional API that the or method throws a NullExceptionError, but I suppose its not that relevant. 
jdk17 Optional: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html#or(java.util.function.Supplier)

Prof, your reply to another comment actually helped me, also thanks @G13nd0n for your comment. Putting these 2 helped me solve my issue.
https://github.com/nus-cs2030/2324-s1/issues/42#issuecomment-1772165465

**Comment by germaineee** [comment]
I think it's because the return type of your or method returns a Maybe<T>, but supplier.get() returns a Maybe<? extends T>, what I did was to change the return type to Maybe<? extends T>, but I'm not sure if that's the right way to do this.
