### ISSUE TITLE
lab 5 ImmutableMap 

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#43]
Do I have to create an ImmutableMap in both Course and Assessment?

**Comment by e0970359** [comment]
i think you have to :)

**Comment by SeawTeng** [comment]
I think Assessment will consist ImmutableMap<String, String> and Course will consist ImmutableMap<String, ImmutableMap<String, String>> which is the course code and the assessment ImmutableMap

**Comment by ChuaLonghorn** [comment]
Having ImmutableMap in both is possible. I started level 1 with Assessment not having ImmutableMap.

**Comment by AbdulrahmanAlRammah** [comment]
You probably will need to. I suggest looking at level 3 to get a better picture of how you can program assessment, student, etc.

**Comment by dianeteo** [comment]
Both methods are possible because getting to level 3 requires you to implement KeyableMap anyway!
