### ISSUE TITLE
Exercise #1: Wrong Output

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#44]
[Exercise #1: Maximum Disc Coverage](https://codecrunch.comp.nus.edu.sg/task_view.php?tid=5563)

<img width="488" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/91947bac-f315-4c98-8922-9cf9867eb0ff">

anyone facing the same error? 

jshell> new Circle(new Point(1, 1), 1).contains(new Point(0, 0))
expected output $.. ==> false
my output new Point ==> null

**Comment by snoopydoooQueen** [comment]
what is in your contains method ?

**Comment by vicelyav** [comment]
Your contains seem to return a new Point instead of a boolean. Maybe check again the output of the contain method?

**Comment by R0yden** [comment]
make sure that the return type of your contains method is correct, and your if-else accounts for all possibilities. Otherwise, there might be a case where you do not return anything, hence giving the null output
