### ISSUE TITLE
Use of Restricted API Collection

### ISSUE THREAD

**Issue by Min-Zong** [nus-cs2030/2324-s1#46]
# Summary

Hi everyone! Can I ask how should we overcome the following problem on codecrunch grader:
Use of restricted API detected.
> java.util.Collection
Grading terminated.

## Description:

It seems that java.util.Collection is found in ImmutableMap.java which was provided to us, but somehow CodeCrunch is banning it and grading could not be proceeded. 

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by ChoonHean** [comment]
Did you use the ImmutableMap values() method? It returns a Collection<V>, so that may be why. Do not use that method if so

**Comment by AbdulrahmanAlRammah** [comment]
I think you should be using methods labeled as public in the ImmutableMap class. Do consult jdk to know how Map.Entry works and iterator.

**Comment by Min-Zong** [comment]
thanks so much!! I think yea I shouldn't use values but should use iterator instead, thanks! :))
