### ISSUE TITLE
Codecrunch rejects any mention of null, even if its not a null pointer

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2030/2324-s1#47]
# Summary
See screenshots

## Description:
_I isolated this particular code to feed into codecrunch, so no its not appearing from elsewhere thats causing the issue_

## Screenshots
| code | codecrunch |
|--------|--------|
| ![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/792fb4f3-5a21-442a-89b1-9fb1c8bf5469)| ![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/daf11e06-b21b-493b-9fb7-6a30c9e29103)|
| ![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/5b4621c2-d6c1-4f1d-84ca-8e081037a223)| ![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/4b8f7023-febd-488b-adde-ff528ef6d140)|

**Comment by PVT-LF** [comment]
It could be the name of the variable `nullCase`. If you see #20 I had an issue with a commented out `instanceof` falsely detected by the grader. I.e. the text `null` gets detected and the grader fails your code.
