### ISSUE TITLE
Is Optional.isEmpty() disabled??

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2030/2324-s1#48]
# Summary
Codecrunch cannot find isEmpty() method from Optional

## Screenshots
![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/238d0c35-34bb-4d11-89cd-3e5a23e914ed)

**Comment by ChoonHean** [comment]
![image](https://github.com/nus-cs2030/2324-s1/assets/145236676/3d4ce988-b80e-4ac4-9709-aa03d35e87a3)
Optional has no such method isEmpty()

**Comment by somethingfishyfishy** [comment]
> ![image](https://user-images.githubusercontent.com/145236676/277100362-3d4ce988-b80e-4ac4-9709-aa03d35e87a3.png) Optional has no such method isEmpty()

**Comment by somethingfishyfishy** [comment]
Maybe you're not using

Java17 API, because java17 API has it
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html

**Comment by somethingfishyfishy** [comment]
> ![image](https://user-images.githubusercontent.com/145236676/277100362-3d4ce988-b80e-4ac4-9709-aa03d35e87a3.png) Optional has no such method isEmpty()

You're using jdk8 API, which is why you couldn't find it lah

**Comment by ChoonHean** [comment]
Whoops, my bad. Then it is probably disabled because programming declaratively does not need it, only imperatively

**Comment by somethingfishyfishy** [comment]
I'm not sure if the fact that it's imperative or declarative programming is relevant

**Comment by ChoonHean** [comment]
I mean, prof has said that we should be programming declaratively, not imperatively, so those methods are disabled for use, since those methods are only relevant in imperative programming

**Comment by somethingfishyfishy** [comment]
You're right.

Optional.isPresent() doesn't work as well, I used another method altogether

**Comment by nearsea00** [comment]
Sorry for the late reply after the issue's already been closed but I wanted to confirm what @ChoonHean said.

It's not stated in the lab exercise, but during the lab session my TAs said that isPresent(), isEmpty(), get() and equals() are all disallowed.

![image](https://github.com/nus-cs2030/2324-s1/assets/145828376/53e251c2-3fec-461c-9ac0-b8225a5edcbd)
