### ISSUE TITLE
Could not get the .bashrc work as instructed

### ISSUE THREAD

**Issue by adamzzq** [nus-cs2030/2324-s1#5]
<img width="1280" alt="01" src="https://github.com/nus-cs2030/2324-s1/assets/110774216/5d8b9572-9ab0-4f87-8903-2c2a842a06c3">
As shown above, I have configured my .bashrc , but when I run 'bash' in the terminal, it does not load the alias command. It only works if I type out the full 'alias checkstyle="java -jar checkstyle-10.3.3-all.jar -c cs2030_checks.xml"'
Could anyone help? Thank you.

**Comment by hwkchia** [comment]
`.bashrc` needs to be in your `$HOME` directory.  So `vim ~/.bashrc` and insert the alias command there.

**Comment by adamzzq** [comment]
Thank you prof! The issue is resolved now
