### ISSUE TITLE
Lab 5: Main: How to read inputs without String split

### ISSUE THREAD

**Issue by vnnamng** [nus-cs2030/2324-s1#51]
# Summary
Square bracket is not allowed on code crunch, I need advice on how to read inputs.

## Description:
I only know String split for such case of uneven space. Or do I have to use token?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by penguinChilin** [comment]
You can use the next() method of Scanner, which returns the next token as a String. The spaces and '\n' will not be included in the token.

**Comment by jodooi** [comment]
Use str = sc.next() for each word, then sc.nextLine() to move on to the next line if needed!

**Comment by WinstonJin** [comment]
you can use a while loop as well so you don't come into any exceptions where the Main class is still trying to take in another value even when there isn't any. 

while(sc.hasNext())

**Comment by somethingfishyfishy** [comment]
If you want a reference, this was the Main file from lab1-lab4 (the Customers and Servers one)

![image](https://github.com/nus-cs2030/2324-s1/assets/143115667/9a9e0056-fb99-4b77-b602-fcbdde947e4d)

You just need to modify accordingly. Good luck!

**Comment by vnnamng** [comment]
Done! Thanks for your helps
