### ISSUE TITLE
Lab 5: Usage of Collection API

### ISSUE THREAD

**Issue by tata32000** [nus-cs2030/2324-s1#53]
# Summary
Does anyone get the error saying "Use of restricted API detected" for lab 5 submission?

## Description:

I have been looking at the Collection document but I don't see that I use Collection api anywhere in my code. The only place I could think of is the add method in the roster class, but that is not from java.util.Collection.

## Screenshots

<img width="647" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/86035967/84a3b5f0-5661-4bde-bb97-4c479ca77386">

**Comment by WinstonJin** [comment]
Can you screenshot your add method?

**Comment by wjunwei2001** [comment]
Do take a look at the ImmutableMap.java file. The values() method returns a Collection. Did you happen to use that method in your code?

**Comment by JerryWang0000** [comment]
Calling Map.Entry can avoid using ImmutableMap::values, and it won't be detected

**Comment by tata32000** [comment]
I actually call values() in my toString() method. Thank you for pointing that out!

**Comment by tata32000** [comment]
Resolved.
