### ISSUE TITLE
Lab 5 restricting java.util.Collections

### ISSUE THREAD

**Issue by Green-Tea-123** [nus-cs2030/2324-s1#54]
# Summary

Lab 5 doesn't allow java.util.Collections to be imported but it's in ImmutableMap.

## Description:

I finished my code to be submitted for lab 5 and then I see that codecrunch failed me because I imported java.util.Collections somewhere. When I went to find where it was imported, I realised that it was in the ImmutableMap class that was given to us for the lab. So, what am I supposed to do now?

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/138492120/f0861462-9502-42d3-8d59-aa53153a3295)

**Comment by YHWong20** [comment]
Might you facing a similar issue to this?
https://github.com/nus-cs2030/2324-s1/issues/53#issue-1955807496

If so, avoid calling values() directly.

**Comment by Green-Tea-123** [comment]
Yeah I just had to avoid using values() to solve the lab.
