### ISSUE TITLE
add() method in Roster class

### ISSUE THREAD

**Issue by schanrui** [nus-cs2030/2324-s1#58]
# Summary

I'm having issues with implementing the logic for the add() method in the Roster class in the case when adding a set of (student, course, assessment grade) if the student already exists in the roster or the course already exists in the student that is in the roster.

## Description:
The add() method works fine for me if i am adding a new student to an existing roster like how it was run in the test cases (adding tony and natasha), but when it comes to the Main class, there are records of the same student with a different course, or the same student with same course but different assessment. in this case, everytime i add a new record, this will replace my existing record of the student with another student. how can i implement my Main class or Roster class to ensure that the assessment is appended instead of replaced?

## Code Snippets
my add method looks sth like this:

public Roster add(String name, String title,
 29             String assessment, String grade) {
 30         Course course = new Course(title).put(new Assessment(assessment, grade));
 31         Student student = new Student(name).put(course);
 32         return this.put(student);
 33     }
 34
 35 }

## Screenshots
![Screenshot 2023-10-24 at 9 35 07 PM](https://github.com/nus-cs2030/2324-s1/assets/144412456/60948322-8f27-49b9-9c1f-d3ffd80c210a)

**Comment by nearsea00** [comment]
Add a few lines of code in your add() method to check if your roster already contains an existing record. If it does, append the new entry onto the existing record. Otherwise, just create a new record. You can use the orElse() method in Optional for this, similar to how you did it for your getGrade() method.

**Comment by schanrui** [comment]
> Add a few lines of code in your add() method to check if your roster already contains an existing record. If it does, append the new entry onto the existing record. Otherwise, just create a new record. You can use the orElse() method in Optional for this, similar to how you did it for your getGrade() method.

I think the problem is how do i directly access the existing student or course within the roster itself? because when i use the get() method for the optional it returns me a new Optional of the value i am accessing instead of referring to the value inside the roster itself?

**Comment by YHWong20** [comment]
Seems like you are overwriting existing entries for each Student.

If a Student's record already exists, and they also have an existing Course record, then you need to account for this. Update each record accordingly, instead of creating a new record that overwrites everything.

**Comment by schanrui** [comment]
> Seems like you are overwriting existing entries for each Student.
> 
> If a Student's record already exists, and they also have an existing Course record, then you need to account for this. Update each record accordingly, instead of creating a new record that overwrites everything.

How do i do that without using the get() method of optional though?

**Comment by nearsea00** [comment]
Use the orElse(arg) method in Optional. It's similar to the get() method in that it returns the value wrapped in the Optional, but if it's an Optional.empty it returns the argument in orElse(arg), which in this case would just be a new record. Check the Java API documentation for more info.

**Comment by schanrui** [comment]
Thanks everyone for your help! Managed to solve it, sorry for the late reply

**Comment by schanrui** [comment]
Thanks everyone for your help! Managed to solve it, sorry for the late reply
