### ISSUE TITLE
Implementing self check out server

### ISSUE THREAD

**Issue by schanrui** [nus-cs2030/2324-s1#59]
# Summary

I am stuck with the logic on generating events for the serve, wait and done events for the self check out as all the self check out counters share the same customer queue and the customer queuing will get served by the first available self checkout.

## Description:
Currently how i implement the self checkout counter is that i have a sub class of the Server class. in this class, it contains an ImList<Pair<Integer, Integer>> of all the self check out server number and their respective next available time. this class acts as a "master" server of all the self checkout counters. it serves a customer by sorting the list of Pairs by their earliest available time. the problem is that i dont know how to maintain the same server for the serve and done events for each customer as the server always changes (see below). 

i tried to change it such that instead of having one server to handle all the self checkouts, each self checkout counter will have its own server class instantiated for it. but i dont know how to maintain that same customer queue for all self checkout counters if they are in different instances? 

## Code Snippets

Attach code snippets (if any)

## Screenshots
here the self check number is different for the serve and done event for the same customer
Screenshots (if any)
![Screenshot 2023-10-24 at 9 55 08 PM](https://github.com/nus-cs2030/2324-s1/assets/144412456/96248226-8d8c-437c-bcd8-276bc4db2ef3)

**Comment by nearsea00** [comment]
Instead of sorting the ImList by time, what if you just iterated through it and returned the element with the earliest available time whenever you need to assign one to a server?

Your implementation differs quite a bit from how I modeled my self-checkouts though so I'm not sure if you'd run into problems later down the line.

**Comment by ChuaLonghorn** [comment]
The self checkout class can be implemented as a subclass of the server class as you are doing. The difference between what you want to do versus what I am doing is that I do not need each self checkout counter to have its own server class instantiated for it.

**Comment by schanrui** [comment]
> The self checkout class can be implemented as a subclass of the server class as you are doing. The difference between what you want to do versus what I am doing is that I do not need each self checkout counter to have its own server class instantiated for it.

but if you do not instantiate your self checkout counter in its own server class how will they take in customers and serve them?

**Comment by schanrui** [comment]
> Instead of sorting the ImList by time, what if you just iterated through it and returned the element with the earliest available time whenever you need to assign one to a server?
> 
> Your implementation differs quite a bit from how I modeled my self-checkouts though so I'm not sure if you'd run into problems later down the line.

did you also do the same thing of having all the self checkouts inside one master server class that controls all the self check out counters or did you have them each instantiated in their own server classes?

**Comment by Yihan2407** [comment]
As the rest have mentioned above, there's a lot of ways to solve this. Some suggestions include:
- Making a "master" server class that takes care of the self-checkout queue for all self-checkout counters
- Having a single self-checkout counter with maxQLength of x (whatever the max Queue length is), while the other self-checkout counters have a maxQLength of 0. Thereafter, you only need to check the number of people in the SC queue from that sole SC counter

**Comment by nearsea00** [comment]
> > Instead of sorting the ImList by time, what if you just iterated through it and returned the element with the earliest available time whenever you need to assign one to a server?
> > Your implementation differs quite a bit from how I modeled my self-checkouts though so I'm not sure if you'd run into problems later down the line.
> 
> did you also do the same thing of having all the self checkouts inside one master server class that controls all the self check out counters or did you have them each instantiated in their own server classes?

Sorry for the late reply, I had each self-checkout instantiated in their own server class, and like @Yihan2407 suggested, I set all but the first self-checkout's max queue to be 0.

**Comment by beefsausagee** [comment]
For SC servers how is the common queue stored. in the instance of creating shld i jst use a string "selfcheckout" and "human" to check the type of servers? since we cant use instanceof

**Comment by vicelyav** [comment]
You may want to try a single check out server to handle all the wait events. For me, difference is that only this wait self checkout can have their queues altered, while the rest cannot be altered (basically you just need to ensure a single check out does the wait events.)

**Comment by schanrui** [comment]
> You may want to try a single check out server to handle all the wait events. For me, difference is that only this wait self checkout can have their queues altered, while the rest cannot be altered (basically you just need to ensure a single check out does the wait events.)

Oh  okay, sounds quite similar to what the others have suggested of having only 1 self check out counter have a customer queue and the rest be set to 0. i will try it out since my current implementation has a lot of problems w the logic, my only concern is are all the servers (human and sco) initialized in the same queue? and if so how will you ensure that only those customers in the sco follow the sco logic? but imma try it out first and seee how it goes

**Comment by schanrui** [comment]
THANKS EVERYONE FOR ALL UR HELP.. aft alm 20h of coding i finally finished this lab :"))
