### ISSUE TITLE
Issues setting up Vim and CheckStyle and cant seem to use CheckStyle

### ISSUE THREAD

**Issue by CodingWhiz1234** [nus-cs2030/2324-s1#6]
# Summary
I am unsure that I have set up Vim and CheckStyle correctly. I also can't seem to use CheckStyle

## Description 
So I followed the steps in "Setting up Vim and Checkstyle" and got the following files. I am lacking the .viminfo file. Not sure if that is important.
![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/82c8b0af-71c1-4cea-8f28-1b7f6a524348)

Next, I tried to run CheckStyle to the HelloWorld.java file. 
So I copied 
alias checkstyle="java -jar checkstyle-10.3.3-all.jar -c cs2030_checks.xml"
into the HelloWorld.java file as shown in the picture below.
![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/783cb506-19a0-483f-a3d1-88995332041d)

After which, I ran 

bash
checkstyle (your filename or *.java)

onto the command prompt but got an error as shown in the picture below. 

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/9bb73743-648b-413e-bb19-08c4ac04d1f4)

Do you have any idea what I have done wrong?

**Comment by hwkchia** [comment]
Drop the brackets. Just `checkstyle HelloWorld.java`

@eLTehh Consider to change?

**Comment by eLTehh** [comment]
Noted, will make the instructions more clear

**Comment by CodingWhiz1234** [comment]
@hwkchia I tried to use checkstyle `HelloWorld.java` as you have suggested and now it says that `bash: checkstyle: command not found` as shown in the figure below.

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/992d5d12-9ff7-47ce-9035-de227de02029)

**Comment by adamzzq** [comment]
Hi, I had a similar issue last week. I think the line 'alias checkstyle="..."' should be saved in your .bashrc file under home directory, instead of the HelloWorld.java file.

**Comment by CodingWhiz1234** [comment]
@adamzzq What you said did help me solve the problem. But now, when I call checkstyle, I get the following error. Do you know how to resolve it?

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/fbdc188c-f17c-44e1-8486-f686106c1f1d)

**Comment by adamzzq** [comment]
I think you do not have HelloWorld.java in the home directory yet. try the command 'ls' to show the contents of your current working directory

**Comment by CodingWhiz1234** [comment]
hmmmmm, i tried the "Is" command and this is what I get

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/df8adb58-a229-448e-87f9-c761fb2de640)

**Comment by adamzzq** [comment]
haha my bad, it's a lower case 'L', not an 'I'. `ls`

**Comment by CodingWhiz1234** [comment]
Ahhhh okay. That works. This is what I get

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/8b06d48c-2cfa-4ef0-993c-a3c3c5d1f517)

**Comment by adamzzq** [comment]
Yes, so there isn't a HelloWorld.java here. You can try `checkstyle Main.java` or `checkstyle Point.java` to test it.

**Comment by CodingWhiz1234** [comment]
Nope, that doesn't seem to solve the problem 
![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/d415b8de-eae6-43c9-9087-e71f80574430)

**Comment by adamzzq** [comment]
> Nope, that doesn't seem to solve the problem ![image](https://user-images.githubusercontent.com/142206064/261974200-d415b8de-eae6-43c9-9087-e71f80574430.png)

Ok, it seems that you are switching between two environments MINGW64 and MINGW32. i think now you are in your MINGW32 environment again where HelloWorld.java exists. so just run `ls` before `checkstyle` to make sure the file that you want to perform a 'checkstyle' is present

**Comment by CodingWhiz1234** [comment]
I see. Okay, I have no idea what is going on. But when I checkstyle in the two different environments, I get two different results

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/35098ac7-4b6a-44d8-8430-164b8c1b5a32)

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/f68176b7-dac0-4577-b8a6-d9db72c955a6)

**Comment by CodingWhiz1234** [comment]
How do I create a new file in MINGW32?

**Comment by CodingWhiz1234** [comment]
Would you possibly be free to have a zoom call? This back and forth chat doesn't seem to be very productive

**Comment by adamzzq** [comment]
`vim blah.java` to create and open blah.java. for the editing and navigation/operations, maybe refer to lecture video

**Comment by adamzzq** [comment]
sorry im still in a lecture now

**Comment by adamzzq** [comment]
> How do I create a new file in MINGW32?

alternatively, run `explorer.exe .`, and create using a notepad/code editor with GUI

**Comment by CodingWhiz1234** [comment]
that's okay. So I created a blah class

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/0d14e965-3bf0-46d9-be60-c41ff3d86588)

escaped from it using :q! and tried to checkstyle. But this is what I got

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/f22d6f77-649d-43c2-9b64-e86ab8f48e0a)

**Comment by adamzzq** [comment]
ummm, you did not save it. `:wq` to save in vim. It wont't save if you force quit by `:q!`

**Comment by CodingWhiz1234** [comment]
Yes! It finally works. I definitely need to spend some time to figure out how vim works but thanks for your time and assistance. It was greatly appreciated!

![image](https://github.com/nus-cs2030/2324-s1/assets/142206064/57e8d7f3-b16a-4aac-9233-9277c063aaf8)

**Comment by adamzzq** [comment]
You're welcome!
