### ISSUE TITLE
Lab 5: Fail Test Case 6

### ISSUE THREAD

**Issue by nearsea00** [nus-cs2030/2324-s1#60]
# Summary

Has anyone run into issues with test case 6 for lab 5?

## Description:

I'm unable to pass test case 6 but the test output doesn't seem to point out any discrepancies between the expected output and actual output.

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/145828376/290c7e51-ddb7-4955-83c6-385436aa623c)

**Comment by somethingfishyfishy** [comment]
You have 1 extra "\n" in your code.

Try System.out.print() instead of System.out.println()

**Comment by nearsea00** [comment]
Ah right, thank you! Dumb mistake
