### ISSUE TITLE
Level3 Error Messages

### ISSUE THREAD

**Issue by IsaacNgSheng** [nus-cs2030/2324-s1#61]
# Summary

I'm abit lost as to going about level3

## Description:

Finished implementing KeyableMap and included them as extensions to Student and Course, however, my jshell gave me a ton of errors upon running.
I don't quite understand how extending KeyableMap results in my symbol not being found 

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/64978175/d6cd93d8-c47a-4141-b89f-5de5d4de9986)

**Comment by nearsea00** [comment]
Do you have a super(...) under your constructors for Course and Student? You have to include otherwise Java will attempt to call an empty constructor KeyableMap() which returns the error "no suitable constructor for KeyableMap(no arguments)" if it's not defined.

**Comment by R0yden** [comment]
As per nearsea00, make sure you have a super constructor with the correct signature. Also, in jshell when working with subclasses, you may also forget to /open the super class!

**Comment by melinenl** [comment]
It could also be the sequence of which you /open your files in jshell  that could result in Course not being found!

**Comment by ChuaLonghorn** [comment]
My KeyableMap implements an interface, so this is different from earlier comments. If KeyableMap inherits from a super class, ensure that there is a super constructor. To test my KeyableMap, I opened the interface along with the KeyableMap in jshell.

**Comment by IsaacNgSheng** [comment]
Thanks for the help guys, it was the super command under my constructor that I lacked
