### ISSUE TITLE
lab5 incompatible type when using multiple .put()

### ISSUE THREAD

**Issue by vvhuiling** [nus-cs2030/2324-s1#64]
# Summary
as following

## Description:

in my KeyableMap class, i write put method as following, but it leads to incompatible type when I try to write the add method in Roster class. 

## Screenshots
![image](https://github.com/nus-cs2030/2324-s1/assets/114858105/1ee931dd-5dbf-49f4-9379-96fd9c6e8596)
<img width="534" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/114858105/7f4c1f86-6d9f-4585-9c0e-84610ce58f74">
!! Incompatible types. Found: 'KeyableMap<Assessment>', required: 'Course'

**Comment by e0958029** [comment]
Could it be that `newCourse.out(assessment)` returns an instance of KeyableMap, but a KeyableMap is NOT a Course, so you cannot assign to newCourse which is of type Course.

**Comment by vvivianfang** [comment]
Could it be because the put method u have in this class does not extend Keyable<Assessment>?

**Comment by nearsea00** [comment]
You have to override the put method in your Course, Student and Roster classes. The method is mostly the exact same but the return type will be a new Course, Student and Roster respectively instead of KeyableMap.
