### ISSUE TITLE
Lab exercise 5

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#65]
![IMAGE 2023-10-26 01:12:45](https://github.com/nus-cs2030/2324-s1/assets/133471507/befcad00-6d7f-4c2a-bad4-b74851691301)
![IMAGE 2023-10-26 01:13:03](https://github.com/nus-cs2030/2324-s1/assets/133471507/af729519-ac70-4311-adee-fb82f6bc4ee9)
Why is my method not returning any exception value?

**Comment by ChoonHean** [comment]
Your optional has a value of Log<T> in it, so orElseThrow will return that value. It will only throw an exception when the optional is empty. For your code, it will only throw an exception if t is null, not when t is of class Log or when String log is null.
