### ISSUE TITLE
Lab 6: Test case 4

### ISSUE THREAD

**Issue by kirin46** [nus-cs2030/2324-s1#66]
Hello, may I know if anyone else had this error? Looking at the correct output, am I right to say that the UnaryOperator rule that is being used in this test case is not the same as the generateRule() defined in the question (since x stays as x)? in that case, then the way I defined gameOfLife should be incorrect? Thank you in advance!

<img width="1323" alt="Screenshot 2023-10-29 at 2 41 51 PM" src="https://github.com/nus-cs2030/2324-s1/assets/120187114/23ce5116-9bd8-4344-874e-a9dbd3baf33d">

**Comment by PVT-LF** [comment]
Yep, the rule being generated as input to the `gameOfLife` method is different from what you defined in your own code.

Just check and ensure that what you use to map `1`s and `0`s to `"x"` and `"."` doesn't reverse the string, which is what seems to be happening in your case.

**Comment by kirin46** [comment]
I see, okay thank you!
