### ISSUE TITLE
Lab 6 Level 4: dealing with immutable List.of()

### ISSUE THREAD

**Issue by schanrui** [nus-cs2030/2324-s1#67]
# Summary

Hi, i managed to implmenet the generateRule method which edits the existing list of integers according to the provided logic, but because the input list in the test cases is a list.of which is immutable, i get an error. how do i edit the immutable list then? (i cant create a new list bc collections and arrays are banned for this lab)

## Code Snippets
this is currently how i generate the gameoflife method using the unary operator of generate rule
![Screenshot 2023-10-31 at 12 48 19 PM](https://github.com/nus-cs2030/2324-s1/assets/144412456/4ec627e3-867e-4495-812b-e94c8e561f23)

## Screenshots
![Screenshot 2023-10-31 at 12 48 05 PM](https://github.com/nus-cs2030/2324-s1/assets/144412456/9a537b2d-03b5-464a-b0a1-2d566fd42579)

Screenshots (if any)

**Comment by AbdulrahmanAlRammah** [comment]
Stream has a toList() method.

**Comment by somethingfishyfishy** [comment]
Your error is in your `generateRule()` method, you may want to employ some of the Stream methods as what the previous commenters mentioned instead of declaratively editing the List.

**Comment by schanrui** [comment]
> Stream has a toList() method.

but isn't the list that comes out of it also an immutable list?

**Comment by somethingfishyfishy** [comment]
It doesn't matter, the process will return you a new List Object, in which you can then streamify and perform your UnaryOperator.apply(T t) again.

**Comment by schanrui** [comment]
Thanks everyone for your help! I managed to solve it with the mapToObj method
