### ISSUE TITLE
lab 06 task 1

### ISSUE THREAD

**Issue by jjiehh** [nus-cs2030/2324-s1#68]
# Summary

hi, could anyone share with me your approach into doing task 1? as im not sure how to find the difference of 2. 

## Description:

my current approach is use rangeClosed from 2 to n then filter based on isPrime then filter based on odd number.

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by PVT-LF** [comment]
You can refer to Recitation 8 Q1 for how to implement an `isPrime()` method using `IntStream`.

Then we just need to find the primes which can be paired with another prime that is larger of smaller than it by 2. I.e. check if there exists a number larger / smaller than that prime by 2 which happens to be a prime as well. Note that the other prime number need not be within the range specified (smaller than n).

**Comment by jjiehh** [comment]
how do u check if there exists a number larger or smaller than that prime by 2? 
what ways can u do that the same prime number can be used more than once, to satisfy different pairs (e.g. 5 paired with 3 OR 7)?

**Comment by garlicsourdough** [comment]
you can add additional logics within the filter to check if the current number has a smaller/larger number by 2 which is also a prime.

**Comment by vvivianfang** [comment]
an approach that i used is rangeClosed and then i filter such that x and x + 2 is both prime numbers and x and x-2 is both prime numbers!

**Comment by JerryWang0000** [comment]
x itself should be prime, and either x+2 or x-2 should be prime
