### ISSUE TITLE
msys setup

### ISSUE THREAD

**Issue by chalmetrs** [nus-cs2030/2324-s1#7]
# Summary
Swap between msys and MINGW32?

## Description 
I followed the installation procedure on the wiki. Typing 'msys' into Powershell opens MINGW32 as the unix environment instead of msys. Jshell still works, but there seem to be extra outputs during testing (numerous ?2004h unlike seen in lecture). Will this be an issue and is there a way to change to msys instead? Thanks!

![image](https://github.com/nus-cs2030/2324-s1/assets/142716318/e9a2fca0-512f-4d81-b5b8-a9f7cf99c880)

**Comment by PVT-LF** [comment]
[What is MSYS?](https://www.msys2.org/)

[What is MinGW?](https://en.wikipedia.org/wiki/MinGW)

> In 2007, a fork of the original MinGW called [Mingw-w64](https://en.wikipedia.org/wiki/Mingw-w64) appeared in order to provide support for 64 bits and new APIs. It has since then gained widespread use and distribution. [MSYS2](https://en.wikipedia.org/wiki/MSYS2) ("minimal system 2") is a software distribution and a development platform for [Microsoft Windows](https://en.wikipedia.org/wiki/Microsoft_Windows), based on Mingw-w64 and [Cygwin](https://en.wikipedia.org/wiki/Cygwin), that helps to deploy code from the [Unix](https://en.wikipedia.org/wiki/Unix) world on Windows.

**Comment by chalmetrs** [comment]
Thanks @PVT-LF but I think my main question is whether a swap can be made, since somehow keying in msys on my command line opens mingw32 instead of msys.

**Comment by PVT-LF** [comment]
> Thanks @PVT-LF but I think my main question is whether a swap can be made, since somehow keying in msys on my command line opens mingw32 instead of msys.

Well, MSYS is based on MinGW and the issue appears more likely to be regarding jshell instead.

**Comment by hwkchia** [comment]
I'm curious to know what is the output of
```
echo $TERM
```

**Comment by chalmetrs** [comment]
@hwkchia It returns 'cygwin'

![image](https://github.com/nus-cs2030/2324-s1/assets/142716318/a8d491b2-32f9-4e6b-9e1b-9b265324ef61)

**Comment by hwkchia** [comment]
see #9
