### ISSUE TITLE
Exercise 5 - Level 1 (of methods)

### ISSUE THREAD

**Issue by Min-Zong** [nus-cs2030/2324-s1#70]
For Level 1, we are expected to create a couple of `of` methods, which I had to use orElseThrow() for both of them, but somehow it caused grading to be terminated as it only allows one. Does anyone know how I could work around this? Thanks!

**Comment by GuoGangQuan** [comment]
do all the check in the log constructor. first use the ofNullable to check if values are null then filter for not same instance lastly do a flatMap to check if log is null using ofNullable. in this way you can craft it with only 1 orElseThrow()

**Comment by Min-Zong** [comment]
got it, thanks a lot!
