### ISSUE TITLE
Ex 4: too many non-private methods

### ISSUE THREAD

**Issue by kirin46** [nus-cs2030/2324-s1#71]
Hi, may I know why this error arises? All the methods I have implemented from the exercise are public but they can't be private or else none of the test cases will pass. Thanks for the help in advance!
<img width="1274" alt="Screenshot 2023-11-02 at 11 30 58 AM" src="https://github.com/nus-cs2030/2324-s1/assets/120187114/63518cd6-1ec0-445a-80d5-21c3164a7f07">

**Comment by shude1999** [comment]
I passed with 10 public methods.

You might have assigned some private functions as public functions.

**Comment by ChoonHean** [comment]
Make sure the only public methods you have are those that the question asks you to define, if you have any more than that, it will trigger that error

**Comment by kirin46** [comment]
Alright, thanks!
