### ISSUE TITLE
lab6 task 3 approach 

### ISSUE THREAD

**Issue by jjiehh** [nus-cs2030/2324-s1#74]
# Summary

i am struggling to get the correct output for countRepeats() method in lab06. 

## Description:

my approach into doing this is using IntStream to get the rangeClosed from 0 to the list.size() - 1 then i filter to check if the current element is same as the previous element then i do .count()

for some reason, i was unable to filter it successfully. 

## Code Snippets
<img width="422" alt="Screenshot 2023-11-03 at 1 14 05 PM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/934bc2f4-a137-42bd-a424-4a8d6e2b6847">
<img width="445" alt="Screenshot 2023-11-03 at 1 14 20 PM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/f3160552-531a-42d8-8687-5b3cf39eab63">

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by nearsea00** [comment]
You're filtering the IntStream, not the list itself

**Comment by nearsea00** [comment]
Also, your implementation wouldn't lead to a correct answer. Even if it worked, you'd end up with 3 when the expected answer is 1. countRepeats() should return the number of groups of consecutive repeated digits. Some examples below to illustrate:
(1, 1, 2, 2) => 2
(1, 2, 2, 1) => 1
(1, 1, 1, 1) => 1
(1, 1, 1, 1, 2, 2) => 2
