### ISSUE TITLE
Indv Proj Wrong Output

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#77]
Hi does anyone know what's wrong with my output? Thanks!

<img width="868" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/847f936e-03e1-40c3-93cc-f72b226d5dc8">

**Comment by JerryWang0000** [comment]
Each line should be separated by '\n'. Also the timestamp should be limited to 3 decimal digits by '%.3f'

**Comment by nearsea00** [comment]
There shouldn't be "customer" in the output either, and it looks like your customer ID starts at 0 instead of 1

**Comment by velouriaa** [comment]
<img width="266" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/d9bc0836-caf7-4786-b3db-d30bef46a2f4">

thanks guys! but why is my timing wrong?

**Comment by nearsea00** [comment]
Your output only has arrive events, either the other events aren't being added to your final String output or you didn't override the toString() method in the other events. Also, it looks like you're skipping the first customer now, since the first arrive event is at 0.314 instead of 0.000

**Comment by velouriaa** [comment]
Thanks. But now I'm getting this output? 

<img width="265" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/e9a264c8-d9cb-4f27-acc0-81dd21243b96">

**Comment by e0958029** [comment]
You have settled your arrive events, now the lab also specifies that there might be other events as well, and you would have to somehow generate those events as well.
