### ISSUE TITLE
Exercise Maybe- Runnable 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#78]
<img width="443" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/73850119-bcd6-478c-8165-67603e73ca7a">

 Hi does anyone know how to implement Runnable? Thank you!

**Comment by nearsea00** [comment]
Runnable doesn't have a generic, just change it to "Runnable action"

**Comment by velouriaa** [comment]
Solved thanks!
