### ISSUE TITLE
Logging Exercise Task 1

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#79]
<img width="363" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/d0ec3492-600a-4a7c-afb4-28a3f4658446">

Hi how do I edit my code such that it returns 
<img width="173" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/9dab5fff-b909-4d61-b211-e3daef995856">

**Comment by vvivianfang** [comment]
u can do "\n" for next line

**Comment by velouriaa** [comment]
Solved thanks!
