### ISSUE TITLE
Clarification on setting up Vim and Checkstyle

### ISSUE THREAD

**Issue by akitachow** [nus-cs2030/2324-s1#8]
Hi there, I wanted to confirm whether Mac users also need to set up Vim and Checkstyle. The reason I'm asking is that the initial command line mentions 'msys', and I recall that Windows users were specifically instructed to install it whereas Mac users were not. I'm a bit inexperienced, so I'm feeling a bit uncertain about what steps I should take. Any assistance you could provide would be greatly appreciated. Thank you!

**Comment by hwkchia** [comment]
Don't worry about checkstyle at the moment. Your tutor will be able to guide you in your first lab.
