### ISSUE TITLE
Exercise Maybe Or Method

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#80]
<img width="563" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/f2077ca9-c118-427f-acc8-760283e1aef6">
 
How do I fix this? Am trying to code the or method. 
Yet another variant is the or method which takes in a Supplier of a Maybe<T> as the alternative.

**Comment by nearsea00** [comment]
I had the same issue, I fixed it by changing it to Maybe<? extends T> instead of just Maybe<T>

**Comment by velouriaa** [comment]
<img width="639" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/f3e8c324-a9ef-49b3-8044-8c27a3809c61">


I'm still getting the same error though

**Comment by penguinChilin** [comment]
You can try getting the type T value out with 2 get()'s, then rewrap it in a Maybe<T>.

**Comment by nearsea00** [comment]
> I had the same issue, I fixed it by changing it to "Maybe<? extends T>" instead of just "Maybe< T >"

I changed the return type in the method definition, so it was `Maybe<? extends T> or(Supplier<? extends Maybe<? extends T>> suppMaybe) {}`

**Comment by velouriaa** [comment]
<img width="635" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/52e7dac1-3cf5-4871-8c04-466bb4d8832c">

Thanks! How shall I fix this error?
