### ISSUE TITLE
Exercise Logging Level 5 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#81]
<img width="365" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/ce01fa02-aec1-47f0-8325-5e495e643ce7">

How do I fix this error? Thanks :)

**Comment by vvivianfang** [comment]
as they r diff types, u cant js add them together. try
Log<Integer> result = sum(n-1) 
then 
int n = result.getT() + n

**Comment by Min-Zong** [comment]
seems like both sum(n - 1) and n need to be of int types, so that ans will also be int type. iirc what I did was to use a map function to perform addition on the integers (value and n), within the `Log` itself.

**Comment by velouriaa** [comment]
<img width="199" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/71d9a363-d6fd-49f7-8ed1-c4308dffacad">

Thanks! I used the map function but why am I now getting this error?

**Comment by nearsea00** [comment]
Did you include a while loop inside your method? All iteration should be happening recursively (the function calling itself, like sum(n) calling sum(n - 1)).

**Comment by ChuaLonghorn** [comment]
The external iteration error means that the answer cannot use a loop. I rewrote the answer to use flatmap for recursion.

**Comment by velouriaa** [comment]
<img width="126" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/f93438ae-3796-407f-9c55-3942062a8659">
<img width="131" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/2ac19027-f167-4bd3-8045-8e7002f4671a">


how do i reverse the order of the printed lines?

**Comment by kirin46** [comment]
i believe for sum, it should be result.flatMap(...)
and for f, it should be (...).flatMap(result)
where result is the recursive call, and the (..) is the change in log

**Comment by velouriaa** [comment]
solved thanks!
