### ISSUE TITLE
What's the difference between .mapToObj() and .forEach()?

### ISSUE THREAD

**Issue by dianeteo** [nus-cs2030/2324-s1#82]

**Comment by nearsea00** [comment]
.forEach() is a void method, it doesn't change the values of the stream (that's what .mapToObj()) does, it just performs an operation for each value

**Comment by Min-Zong** [comment]
I think `.mapToObj()` helps to transform each element of a stream into another object, whereas `forEach()` performs an action on each element within the stream but does not return anything (thus being a void method).

**Comment by ChuaLonghorn** [comment]
mapToObj() takes an IntFunction, LongFunction, or DoubleFunction as an argument to apply it on each element of the primitive stream, therefore getting a new object stream. 

forEach() takes a Consumer as an argument applied to each element in the stream. This method will not return a new stream, it consumes elements and has side effects like output (printing) elements.

**Comment by darenkoh23** [comment]
Main difference is:
forEach():  perform an action on each element of a stream
mapToObj(): transform the elements of a primitive stream to objects.
