### ISSUE TITLE
Lab4: Multiple output detected

### ISSUE THREAD

**Issue by viniciusat3** [nus-cs2030/2324-s1#85]
Has anyone faced the compilation error "Multiple output detected" for lab4?

I don't understand the error, since the output of my simulate method inside the Simulator class is a single String. I am not printing multiple times throughout the code execution - I assumed that's what this error means.

Anyone can help? Thanks

**Comment by e0958029** [comment]
Could there be a System.out.println anywhere that you forgot to comment out for debugging purposes, those count as extra outputs?

**Comment by viniciusat3** [comment]
There was a method with a System.out.println that wasn't being used anymore, but got flagged in codecrunch. Just fixed it
