### ISSUE TITLE
Logging Level 1

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#89]
<img width="609" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/f9637032-5580-4195-adc6-f745ac751fcf">

Hi how do I fix my code? Thanks!
I did return "Log[" + this.value + "] \n" + this.log;

**Comment by DarkAxel01** [comment]
When the log is empty it should just return Log[this.value] without the \n. The \n is only used when there is a log involved.

**Comment by velouriaa** [comment]
<img width="647" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/0a25b6fc-52bf-41c6-a53d-5d3bd75c5227">


thanks! im still getting this error though

**Comment by DarkAxel01** [comment]
I think there is a space in ur code. "] \n" -> "]\n"

**Comment by velouriaa** [comment]
thanks! how do i solve this error? how do i use Optional.ofNullable?

<img width="403" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/d8f32a8f-070b-4023-8c1e-d2c72f24f108">

**Comment by DarkAxel01** [comment]
basically Optional.ofNullable checks whether ur inputs is null or not. If is null, it returns Optional.empty() and if is not null, it will pass through and return an Optional wrapped value. Basically, u can do Optional.ofNullable(input value).map/filter etc to find ur answer.

**Comment by velouriaa** [comment]
how do i use flatmap to check if the log is null?

**Comment by velouriaa** [comment]
thanks! i have 2 approaches, not sure what is wrong with both 

static <T> Log<T> of(T value, String log) {
          return Optional.ofNullable(value).filter(value instanceof Log).flatMap(x -> x == null).flatMap(z -> Optional.of(new        Log<T>(value,log))).orElseThrow(new IllegalArgumentException("Invalid arguments"));

The above has an error with flatMap 

return Optional.ofNullable(value).flatMap(x -> Optional.ofNullable(log).map(z -> Optional.of(new Log<T>(value,log)))).
    orElseThrow(new IllegalArgumentException("Invalid arguments"));

<img width="960" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/4a6c3291-2a41-469c-957d-519fe1f4b156">

**Comment by saddle196883** [comment]
For your first one:
```java
static Log of(T value, String log) {
   return Optional
        .ofNullable(value)
        .filter(value instanceof Log) // Don't use raw types, Log<?> instead of Log
        .flatMap(x -> x == null) // Using null will make the code not compile, use another Optional.ofNullable
        .flatMap(z -> Optional.of(new Log(value,log)))
        .orElseThrow(new IllegalArgumentException("Invalid arguments")); // orElseThrow takes in a Supplier
```
Essentially, you should be using two Optional.ofNullable for the two arguments, and weave them together (flatMap is the only way we know to do this).

For your second one, 
```java
static Log of(T value, String log) {
    return Optional
        .ofNullable(value)
        .flatMap(x -> Optional
            .ofNullable(log)
            .map(z -> Optional.of(new Log(value,log)))) // What if value is a Log<?>? Also don't use raw types
        .orElseThrow(new IllegalArgumentException("Invalid arguments")); // orElseThrow takes in a Supplier
```

(Also, it is nice etiquette to indent/format your code properly to make it more readable to whoever is helping you debug.)

**Comment by velouriaa** [comment]
thanks! how do i make orElseThrow take in a Supplier?

**Comment by saddle196883** [comment]
You can just define a new ``Supplier<Exception>`` and feed it in the method like
```java
new Supplier<Exception>() {
    Exception get() {
        return new Exception("exceptions should be exceptional");
    }
}
```

But since ``Supplier<Exception>`` is a functional interface, we can replace it with a lambda function, the above is equivalent to:
```java
() -> new Exception("exceptions should be exceptional")
```

**Comment by velouriaa** [comment]
thanks but im now getting this error 
<img width="925" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/1bce8612-a340-40a3-bb48-24bfd55f400c">

**Comment by saddle196883** [comment]
Likely the problem is not with the ``orElseThrow``.

**Comment by velouriaa** [comment]
solved thanks
