### ISSUE TITLE
Natural Numbers succ method 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#90]
What should I return if  either operands is invalid? Im getting the error below 
<img width="838" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/33cbd28c-b85e-4a91-b986-aca15456f051">

**Comment by Yihan2407** [comment]
If I remember correctly, you just return an Optional.<Integer>empty(), which is the equivalent of an NaN in the context of Num and AbstractNum

**Comment by andreelim** [comment]
Perhaps you could directly use the constructor instead of using the `of` method?  `of` takes in integers, not optionals

**Comment by velouriaa** [comment]
solved thanks
