### ISSUE TITLE
MOCK PA2 -- Compilation Error: Use of restricted Optional methods

### ISSUE THREAD

**Issue by andreelim** [nus-cs2030/2324-s1#92]
Hi, can i check what are restricted Optional methods? I am trying to get around this error..

![Screenshot 2023-11-09 at 2 51 48 AM](https://github.com/nus-cs2030/2324-s1/assets/85007504/1f58956f-9e98-4e83-b4aa-f200c4d1969f)

**Comment by PVT-LF** [comment]
>Other Constraints
The following are the usual constraints. You should keep to the constructs and programming discipline instilled throughout the module.

Write each class/interface in its own file.
Ensure that ALL object properties and class constants are declared private final.
Ensure that that your classes are NOT cyclic dependent.
ONLY the following java libraries ARE allowed:
java.lang
java.util.List
java.util.Optional
java.util.stream.Stream, and
functional interfaces from java.util.function.
Use &&, || and ! in logical expressions.
You are NOT allowed to use java keywords/literals: null, instanceof
You are NOT allowed to use Java reflection, i.e. Object::getClasses and other methods from Class
You are NOT allowed to use * wildcard imports.
You are NOT allowed to define anonymous inner classes; define lambdas instead.
You are NOT allowed to define array constructs, e.g. String[] or using ellipsis, e.g.String...

**Comment by jr-kong** [comment]
I think another reason for this error is when u dont define the type parameter when doing Optional.of. so u need to do
Optional.<Integer>of(1) or Optional.<Boolean>of(true) for example

**Comment by andreelim** [comment]
Okay thanks!
