### ISSUE TITLE
Lab 7 Mock PA2 add(Num num) method

### ISSUE THREAD

**Issue by schanrui** [nus-cs2030/2324-s1#94]
# Summary

I am trying to use and IntStream to successively add 1 to the current num for my add method, but I am having problems obtaining the value boxed within the optional value of the num input. I know we are not allowed to use any get() related methods in Optional class even orElse() is not allowed. anyone who encoutered a similiar issue for this method able to provide some advice on how to get the nested integer value of the optional num without using get methods? thanks

## Code Snippets
![Screenshot 2023-11-09 at 12 40 05 PM](https://github.com/nus-cs2030/2324-s1/assets/144412456/c0d79b7a-fca7-4862-bef5-74c0ca442eb2)

![Screenshot 2023-11-09 at 12 40 21 PM](https://github.com/nus-cs2030/2324-s1/assets/144412456/84347864-9eda-43aa-9bf6-e5efee073f2c)

**Comment by Yihan2407** [comment]
Hi, as far as I know there isn't a way to unwrap the Integer from the Optional<Integer> without using getter methods, which are all unfortunately banned. The closest thing might be using Optional.stream() which will return you a stream of just the wrapped integer, but I'm not sure if it'll help you in your implementation (I'm honestly not even sure if this is banned or not)

One more point, forEach takes in a consumer and does not return a value. If I remember correctly, succ() returns another Num meaning that you need some way to re-assign your current Num to the new Num from succ(). To my understanding, when you use forEach, it isn't able to return you your desired value of Num after multiple iterations of succ() as you are not able to re-assign the value.

**Comment by schanrui** [comment]
Thanks guys for ur help! Managed to solve it using a while loop instead haha

**Comment by ChinSekYi** [comment]
Hello! Ik this issue is closed but, just as @Yihan2407 mentioned, you can use streams. One way to get the value out of an optional is to use map/flatMap. Hope that helps!
