### ISSUE TITLE
Mock PA#2 Sub method 

### ISSUE THREAD

**Issue by velouriaa** [nus-cs2030/2324-s1#95]
<img width="206" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/147584805/474fbadc-638c-4188-8f8b-2375ae980438">

Hi how do I fix this error? thanks!

**Comment by Clementpng** [comment]
Hi, I think you could make use of Optional's filter and AbstractNum's "valid" Predicate to check whether the resulting Integer is valid. An invalid Integer would result in Optional empty being returned, which you can then use to construct a new Num to return
