### ISSUE TITLE
Mock PA2: Level 1 one() method

### ISSUE THREAD

**Issue by germaineee** [nus-cs2030/2324-s1#97]
For the one method, are we not allowed to use the constructor that takes in an int and input 1 as the argument?

**Comment by AbdulrahmanAlRammah** [comment]
No, the restrictions say you can't use int anywhere. However, you do have succ and other useful methods.

**Comment by germaineee** [comment]
ok solved thankyou!

**Comment by germaineee** [comment]
ok solved thankyou!
