### ISSUE TITLE
MOCK PRACTICAL level 3

### ISSUE THREAD

**Issue by e0970359** [nus-cs2030/2324-s1#98]
my code returns zero.sub(one) = -1 instead of NAN even after i checked for validity , does anyone know why?

**Comment by PVT-LF** [comment]
You did not check for validity after doing the subtraction. One way is to use `Num.of(result)` at the end so -1 becomes `NaN`.

**Comment by e0970359** [comment]
i added the validity check after doing the subtraction as well. After i found the result , i check if (result.isValid()) , but still doesnt work

**Comment by saddle196883** [comment]
After checking if the result is valid, what did you do?
